
name: "CMake Build and Test"
description: "Build and tests the DVC Bucketing Lib"
runs:
  using: "composite"
  strategy:
    matrix:
      os: [ ubuntu-latest, macos-12 ]
  runs-on: ${{ matrix.os }}
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./dvctest